In [33]:
import zipfile   
import os       

zip_path = "german_data.zip"          
extract_path = "german_data"          

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

In [28]:
os.listdir(extract_path)

['german.data', 'german.data-numeric', 'german.doc', 'Index']

In [34]:
import pandas as pd

file_path = os.path.join(extract_path, "german.data")

df = pd.read_csv(file_path, sep=" ", header=None)

In [35]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,A11,6,A34,A43,1169,A65,A75,4,A93,A101,...,A121,67,A143,A152,2,A173,1,A192,A201,1
1,A12,48,A32,A43,5951,A61,A73,2,A92,A101,...,A121,22,A143,A152,1,A173,1,A191,A201,2
2,A14,12,A34,A46,2096,A61,A74,2,A93,A101,...,A121,49,A143,A152,1,A172,2,A191,A201,1
3,A11,42,A32,A42,7882,A61,A74,2,A93,A103,...,A122,45,A143,A153,1,A173,2,A191,A201,1
4,A11,24,A33,A40,4870,A61,A73,3,A93,A101,...,A124,53,A143,A153,2,A173,2,A191,A201,2

In [31]:
df.shape

(1000, 21)

In [36]:
df.columns = [
    "Status", "Duration", "CreditHistory", "Purpose",
    "CreditAmount", "Savings", "Employment", "InstallmentRate",
    "PersonalStatus", "Debtors", "Residence",
    "Property", "Age", "InstallmentPlans", "Housing",
    "ExistingCredits", "Job", "Dependents",
    "Telephone", "ForeignWorker", "Risk"
]

In [22]:
def risk_label(value):
    if value == 1:
        return "Low"
    else:
        return "High"

df["Risk"] = df["Risk"].apply(risk_label)

In [37]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

for col in df.columns:
    if df[col].dtype == "object":
        df[col] = encoder.fit_transform(df[col])

In [24]:
X = df.drop("Risk", axis=1)   
y = df["Risk"]

In [38]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [39]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=100,   # Number of trees
    random_state=42
)

model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [40]:
y_pred = model.predict(X_test)

In [41]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.805

In [42]:
importance_df

             Feature  Importance
4       CreditAmount    0.131240
12               Age    0.104386
0             Status    0.103118
1           Duration    0.095828
3            Purpose    0.066581
2      CreditHistory    0.061481
6         Employment    0.055956
5            Savings    0.049017
11          Property    0.047091
10         Residence    0.043563
7    InstallmentRate    0.042611
8     PersonalStatus    0.033586
16               Job    0.032321
14           Housing    0.028624
13  InstallmentPlans    0.026188
15   ExistingCredits    0.020973
18         Telephone    0.020619
9            Debtors    0.018796
17        Dependents    0.013886
19     ForeignWorker    0.004134